function tmuxhelp --description 'Show tmux cheatsheet'
    echo '╔══════════════════════════════════════════════════════════════╗'
    echo '║                    TMUX CHEATSHEET                           ║'
    echo '║              Custom config: ~/.tmux.conf                     ║'
    echo '╚══════════════════════════════════════════════════════════════╝'
    echo ''
    echo '┌─ PREFIX ─────────────────────────────────────────────────────┐'
    echo '│ Ctrl+a                    Your custom prefix (not Ctrl+b)    │'
    echo '└──────────────────────────────────────────────────────────────┘'
    echo ''
    echo '┌─ SESSIONS ───────────────────────────────────────────────────┐'
    echo '│ tmux                      Start new session                  │'
    echo '│ tmux new -s <name>        Start new named session            │'
    echo '│ tmuxa <name>              Attach to session (alias)          │'
    echo '│ tmuxl                     List sessions (alias)              │'
    echo '│ tmuxk <name>              Kill session (alias)               │'
    echo '│ <prefix> d                Detach from session                │'
    echo '│ <prefix> $                Rename session                     │'
    echo '└──────────────────────────────────────────────────────────────┘'
    echo ''
    echo '┌─ WINDOWS ────────────────────────────────────────────────────┐'
    echo '│ <prefix> c                Create new window                  │'
    echo '│ <prefix> ,                Rename window                      │'
    echo '│ <prefix> w                List windows                       │'
    echo '│ <prefix> n                Next window                        │'
    echo '│ <prefix> p                Previous window                    │'
    echo '│ <prefix> &                Kill window                        │'
    echo '│ <prefix> 0-9              Switch to window by number         │'
    echo '└──────────────────────────────────────────────────────────────┘'
    echo ''
    echo '┌─ PANES (CUSTOM) ─────────────────────────────────────────────┐'
    echo '│ <prefix> |                Split vertically                   │'
    echo '│ <prefix> -                Split horizontally                 │'
    echo '│ <prefix> x                Kill pane                          │'
    echo '│ <prefix> z                Toggle pane zoom                   │'
    echo '│ <prefix> m                Maximize pane toggle               │'
    echo '│ <prefix> h                Resize pane left                   │'
    echo '│ <prefix> j                Resize pane down                   │'
    echo '│ <prefix> k                Resize pane up                     │'
    echo '│ <prefix> l                Resize pane right                  │'
    echo '│ Ctrl+h/j/k/l              Navigate panes (vim-tmux-navigator)│'
    echo '└──────────────────────────────────────────────────────────────┘'
    echo ''
    echo '┌─ COPY MODE (VI) ─────────────────────────────────────────────┐'
    echo '│ <prefix> [                Enter copy mode                    │'
    echo '│ Space                     Start selection                    │'
    echo '│ v                         Begin selection (in copy mode)     │'
    echo '│ y                         Toggle rectangle mode              │'
    echo '│ Enter                     Copy selection (to clipboard)      │'
    echo '│ <prefix> P                Paste from buffer                  │'
    echo '│ q                         Exit copy mode                     │'
    echo '└──────────────────────────────────────────────────────────────┘'
    echo ''
    echo '┌─ MISC ───────────────────────────────────────────────────────┐'
    echo '│ <prefix> r                Reload tmux config                 │'
    echo '│ <prefix> ?                Show all keybindings               │'
    echo '│ <prefix> t                Show time                          │'
    echo '│ <prefix> :                Command prompt                     │'
    echo '└──────────────────────────────────────────────────────────────┘'
    echo ''
    echo '┌─ PLUGINS ────────────────────────────────────────────────────┐'
    echo '│ vim-tmux-navigator        Seamless vim/tmux navigation       │'
    echo '│ tmux-resurrect            Persist sessions after restart     │'
    echo '│ tmux-continuum            Auto-save sessions every 15min     │'
    echo '│ tmux-gruvbox              Gruvbox dark theme                 │'
    echo '└──────────────────────────────────────────────────────────────┘'
    echo ''
    echo 'Tip: Mouse support is enabled - you can click to switch panes!'
end
